### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by mghersi** [adrianhuber17/webSocket-App#1]
Hi

I would like to know how to run this App in Heroku.
Thanks, Mario

**Comment by adrianhuber17** [comment]
Hi Mario,

Yes it should be possible to deploy this app on Heroku.

I have a similar app, except it is not using WebSocket communication, that I deployed on Heroku and you can check out the code in my GitHub.
GitHub: https://github.com/adrianhuber17/daily-log-app 
Website: https://getlog2305.herokuapp.com/
This should give you a sense on how I deployed a similar set up (Flask,React,PostgreSQL,Docker,gunicorn,Nginx) to Heroku, unfortunately I don't have documentation for it yet.

Essentially I used gunicorn to serve my Flask service, Nginx to serve React. I then utilized Docker to build an image of my app with 3 services (React,Flask,PostgreSQL). Then I used Heroku Container Registry to deploy the app using the Docker image. (https://devcenter.heroku.com/articles/container-registry-and-runtime)

I am currently in the process of deploying an app with Flask, React that uses WebSockets. Once I have more info on how I deployed it to Heroku I will reach out to you.

Hope this helps.
Thanks,

Adrian
